# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poc_grpc_example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='poc_grpc_example.proto',
  package='poc_grpc_example',
  syntax='proto3',
  serialized_options=b'\n!io.grpc.examples.poc_grpc_exampleB\023PocGrpcExampleProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16poc_grpc_example.proto\x12\x10poc_grpc_example\"2\n\x11InsertUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"%\n\x12InsertUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x0fGetUserResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t2\xb6\x01\n\x07Greeter\x12Y\n\nInsertUser\x12#.poc_grpc_example.InsertUserRequest\x1a$.poc_grpc_example.InsertUserResponse\"\x00\x12P\n\x07GetUser\x12 .poc_grpc_example.GetUserRequest\x1a!.poc_grpc_example.GetUserResponse\"\x00\x42@\n!io.grpc.examples.poc_grpc_exampleB\x13PocGrpcExampleProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_INSERTUSERREQUEST = _descriptor.Descriptor(
  name='InsertUserRequest',
  full_name='poc_grpc_example.InsertUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poc_grpc_example.InsertUserRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='surname', full_name='poc_grpc_example.InsertUserRequest.surname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=94,
)


_INSERTUSERRESPONSE = _descriptor.Descriptor(
  name='InsertUserResponse',
  full_name='poc_grpc_example.InsertUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='poc_grpc_example.InsertUserResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=133,
)


_GETUSERREQUEST = _descriptor.Descriptor(
  name='GetUserRequest',
  full_name='poc_grpc_example.GetUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='poc_grpc_example.GetUserRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=163,
)


_GETUSERRESPONSE = _descriptor.Descriptor(
  name='GetUserResponse',
  full_name='poc_grpc_example.GetUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poc_grpc_example.GetUserResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='surname', full_name='poc_grpc_example.GetUserResponse.surname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['InsertUserRequest'] = _INSERTUSERREQUEST
DESCRIPTOR.message_types_by_name['InsertUserResponse'] = _INSERTUSERRESPONSE
DESCRIPTOR.message_types_by_name['GetUserRequest'] = _GETUSERREQUEST
DESCRIPTOR.message_types_by_name['GetUserResponse'] = _GETUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertUserRequest = _reflection.GeneratedProtocolMessageType('InsertUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTUSERREQUEST,
  '__module__' : 'poc_grpc_example_pb2'
  # @@protoc_insertion_point(class_scope:poc_grpc_example.InsertUserRequest)
  })
_sym_db.RegisterMessage(InsertUserRequest)

InsertUserResponse = _reflection.GeneratedProtocolMessageType('InsertUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSERTUSERRESPONSE,
  '__module__' : 'poc_grpc_example_pb2'
  # @@protoc_insertion_point(class_scope:poc_grpc_example.InsertUserResponse)
  })
_sym_db.RegisterMessage(InsertUserResponse)

GetUserRequest = _reflection.GeneratedProtocolMessageType('GetUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUEST,
  '__module__' : 'poc_grpc_example_pb2'
  # @@protoc_insertion_point(class_scope:poc_grpc_example.GetUserRequest)
  })
_sym_db.RegisterMessage(GetUserRequest)

GetUserResponse = _reflection.GeneratedProtocolMessageType('GetUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERRESPONSE,
  '__module__' : 'poc_grpc_example_pb2'
  # @@protoc_insertion_point(class_scope:poc_grpc_example.GetUserResponse)
  })
_sym_db.RegisterMessage(GetUserResponse)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='poc_grpc_example.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=216,
  serialized_end=398,
  methods=[
  _descriptor.MethodDescriptor(
    name='InsertUser',
    full_name='poc_grpc_example.Greeter.InsertUser',
    index=0,
    containing_service=None,
    input_type=_INSERTUSERREQUEST,
    output_type=_INSERTUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='poc_grpc_example.Greeter.GetUser',
    index=1,
    containing_service=None,
    input_type=_GETUSERREQUEST,
    output_type=_GETUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
