# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import poc_grpc_example_pb2 as poc__grpc__example__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertUser = channel.unary_unary(
                '/poc_grpc_example.Greeter/InsertUser',
                request_serializer=poc__grpc__example__pb2.InsertUserRequest.SerializeToString,
                response_deserializer=poc__grpc__example__pb2.InsertUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/poc_grpc_example.Greeter/GetUser',
                request_serializer=poc__grpc__example__pb2.GetUserRequest.SerializeToString,
                response_deserializer=poc__grpc__example__pb2.GetUserResponse.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def InsertUser(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertUser': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertUser,
                    request_deserializer=poc__grpc__example__pb2.InsertUserRequest.FromString,
                    response_serializer=poc__grpc__example__pb2.InsertUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=poc__grpc__example__pb2.GetUserRequest.FromString,
                    response_serializer=poc__grpc__example__pb2.GetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poc_grpc_example.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def InsertUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poc_grpc_example.Greeter/InsertUser',
            poc__grpc__example__pb2.InsertUserRequest.SerializeToString,
            poc__grpc__example__pb2.InsertUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poc_grpc_example.Greeter/GetUser',
            poc__grpc__example__pb2.GetUserRequest.SerializeToString,
            poc__grpc__example__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
